### ISSUE TITLE
404 on forecast block example

### ISSUE THREAD

**Issue by kuanb** [assembleapp/registry#16]
`POST https://assembleapp.co/blocks/3/runs.json 404 ()`

Location: https://assembleapp.co/blocks/3

Response box does not indicate that POST failed, leaves run pending text up, does not let user know response was 404. Screen cap:
![image](https://user-images.githubusercontent.com/6053396/27050400-31fece02-4f67-11e7-8c90-94c9b4bb6160.png)

Command line:
```
$ curl \
>   'https://assembleapp.co/blocks/3/runs.json' \
>   -X POST \
>   -H "Content-Type: application/json" \
>   -H "Accept: application/json" \
>   -H "Authorization: Bearer b27bdbe3b1dce94f3845958f10a60c4a" \
>   -d '{
>   "data": {
>     "latitude": "47.606",
>     "longitude": "-122.33",
>     "darksky_key": "d40ec580b195e3d966ad9f084136a19f"
>   }
> }'
{"status":404,"error":"Not Found"}
```

**Comment by c-lliope** [comment]
Thanks for reporting! This'll be taken care of by the end of the week.
