### ISSUE TITLE
Upgrade "Inactive/active" switch

### ISSUE THREAD

**Issue by c-lliope** [assembleapp/registry#21]
Reported by @mattyayoh

**Comment by MattyAyOh** [comment]
Quick solution: Make text always say "Active", so it's either checked or unchecked

Or use a switch:
![screen shot 2017-06-19 at 2 25 11 pm](https://user-images.githubusercontent.com/5342037/27299667-1c9bbbbc-54fb-11e7-9026-97b20d3c93e0.png)



Or a segmented control:
![screen shot 2017-06-19 at 2 24 06 pm](https://user-images.githubusercontent.com/5342037/27299632-f8a01c94-54fa-11e7-8d9c-b0aad8059b49.png)

**Comment by c-lliope** [comment]
How about this? (=

![toggle](https://user-images.githubusercontent.com/829576/27304611-a052d470-550c-11e7-9110-ced720e73044.gif)

Just pushed it live to the site.

**Comment by MattyAyOh** [comment]
![](http://i.imgur.com/SdrKyvD.gif)
